services:
  nginx:
    build: ./nginx
    container_name: nginx-mdss
    ports:
      - "127.0.0.1:1935:1935"
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/stat.xsl:/etc/nginx/mdss/stat.xsl:ro
      - ./nginx/site:/etc/nginx/mdss/site

  flask:
    build: ./flask
    container_name: flask-mdss
    volumes:
      - avatars:/mdss/app/static/avatar

volumes:
  avatars: