services:
  nginx:
    build: ./nginx
    container_name: nginx-mdss
    ports:
      - "1935:1935"
      - "8080:80"
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    volumes:
      - ./nginx/stat.xsl:/etc/nginx/mdss/stat.xsl:ro
      - ./nginx/site:/etc/nginx/mdss/site

  flask:
    build: ./flask
    container_name: flask-mdss
    environment:
      SECRET_KEY: ${SECRET_KEY:-}
      BASE_ADDRESS: ${BASE_ADDRESS:-http://localhost:8080}
    volumes:
      - avatars:/mdss/app/static/avatar
      - db:/mdss/instance

volumes:
  avatars:
  db: